CREATE TABLE DATOS_ENCUESTA_DESCRIPCIONES AS 
SELECT  
ENC.SEQN_EXAMINATION, 
ENC.PESO_KG, 
ENC.ALTURA_DE_PIE_CM, 
ENC.INDICE_MASA_CORPORAL,
ENC.CATEGORIA_IMC, 
CAT1.DESCRIPCION AS DESC_CATEGORIA_IMC,
ENC.GENERO,
CAT2.DESCRIPCION AS DESC_GENERO,
ENC.EDAD_ANIOS,
ENC.RAZA_ORIGEN_HISPANO,
CAT3.DESCRIPCION AS DESC_RAZA_ORIGEN_HISPANO,
ENC.PAIS_NACIMIENTO,
CAT4.DESCRIPCION AS DESC_PAIS_NACIMIENTO,
ENC.NIVEL_EDUCATIVO_6_19_ANIOS,
CAT5.DESCRIPCION AS DESC_NIVEL_EDUCATIVO_6_19_ANIO,
ENC.NUMERO_PERSONAS_HOGAR,
CAT6.DESCRIPCION AS DESC_NUMERO_PERSONAS_HOGAR,
ENC.INGRESO_ANUAL_HOGAR,
CAT7.DESCRIPCION AS DESC_INGRESO_ANUAL_HOGAR,
ENC.ASISTE_JARDIN_INF_ESCUELA_SECU,
CAT8.DESCRIPCION AS DESC_ASIST_JARDIN_INF_ESC_SECU,
ENC.ESCUELA_SIRVE_ALMUERZO,
CAT9.DESCRIPCION AS DESC_ESCUELA_SIRVE_ALMUERZO,
ENC.NUM_VECES_SEM_ALMUERZO_ESCOLAR,
CAT10.DESCRIPCION AS DESC_NUM_VECES_SEM_ALMUE_ESCU,
ENC.ESCUELA_SIRVE_DESAYUNO_DIARIO,
CAT11.DESCRIPCION AS DESC_ESCU_SIRVE_DESAYUN_DIARIO,
ENC.NUM_VECES_SEM_DESAYUNO_ESCOLAR,
CAT12.DESCRIPCION AS DESC_NUM_VECES_SEM_DESAYU_ESCU,
ENC.NUM_COMIDAS_NO_PREPARADA_CASA,
CAT13.DESCRIPCION AS DESC_NUM_COMIDA_NO_PREPARA_CASA,
ENC.NUM_COMIDAS_RAPIDA_PIZZERIA,
CAT14.DESCRIPCION AS DESC_NUM_COMIDA_RAPID_PIZZERIA,
ENC.DIAS_FISIC_ACTIVO_ALMENOS_60MIN,
CAT15.DESCRIPCION AS DESC_DIA_FISIC_ACTIV_ALM_60MIN,
ENC.HORAS_MIRA_TV_VIDEO_ULT_30DIAS,
CAT16.DESCRIPCION AS DESC_HORAS_TV_VIDEO_ULT_30DIAS,
ENC.HORAS_COMPUTADOR_ULT_30DIAS,
CAT17.DESCRIPCION AS DESC_HORAS_COMPUTAD_ULT_30DIAS
FROM DATOS_ENCUESTA ENC
INNER JOIN CATALOGO_VARIABLE CAT1 ON CAT1.CODIGO = ENC.CATEGORIA_IMC AND CAT1.CATEGORIA_VARIABLE = 'Categoría IMC - Niños / Jóvenes'
INNER JOIN CATALOGO_VARIABLE CAT2 ON CAT2.CODIGO = ENC.GENERO AND CAT2.CATEGORIA_VARIABLE = 'Género'
INNER JOIN CATALOGO_VARIABLE CAT3 ON CAT3.CODIGO = ENC.RAZA_ORIGEN_HISPANO AND CAT3.CATEGORIA_VARIABLE = 'Raza / origen hispano'
INNER JOIN CATALOGO_VARIABLE CAT4 ON CAT4.CODIGO = ENC.PAIS_NACIMIENTO AND CAT4.CATEGORIA_VARIABLE = 'País de nacimiento'
INNER JOIN CATALOGO_VARIABLE CAT5 ON CAT5.CODIGO = ENC.NIVEL_EDUCATIVO_6_19_ANIOS AND CAT5.CATEGORIA_VARIABLE = 'Nivel educativo - Niños / Jóvenes 6-19'
INNER JOIN CATALOGO_VARIABLE CAT6 ON CAT6.CODIGO = ENC.NUMERO_PERSONAS_HOGAR AND CAT6.CATEGORIA_VARIABLE = 'Número total de personas en el hogar'
INNER JOIN CATALOGO_VARIABLE CAT7 ON CAT7.CODIGO = ENC.INGRESO_ANUAL_HOGAR AND CAT7.CATEGORIA_VARIABLE = 'Ingreso Anual del Hogar'
INNER JOIN CATALOGO_VARIABLE CAT8 ON CAT8.CODIGO = ENC.ASISTE_JARDIN_INF_ESCUELA_SECU AND CAT8.CATEGORIA_VARIABLE = 'Asiste al jardín de infantes hasta la escuela secundaria'
INNER JOIN CATALOGO_VARIABLE CAT9 ON CAT9.CODIGO = ENC.ESCUELA_SIRVE_ALMUERZO AND CAT9.CATEGORIA_VARIABLE = 'La escuela sirve almuerzos escolares'
INNER JOIN CATALOGO_VARIABLE CAT10 ON CAT10.CODIGO = ENC.NUM_VECES_SEM_ALMUERZO_ESCOLAR AND CAT10.CATEGORIA_VARIABLE = 'Número de veces / semana recibe almuerzo escolar'
INNER JOIN CATALOGO_VARIABLE CAT11 ON CAT11.CODIGO = ENC.ESCUELA_SIRVE_DESAYUNO_DIARIO AND CAT11.CATEGORIA_VARIABLE = 'La escuela sirve desayuno completo cada día'
INNER JOIN CATALOGO_VARIABLE CAT12 ON CAT12.CODIGO = ENC.NUM_VECES_SEM_DESAYUNO_ESCOLAR AND CAT12.CATEGORIA_VARIABLE = 'Número de veces / semana recibe desayuno escolar'
INNER JOIN CATALOGO_VARIABLE CAT13 ON CAT13.CODIGO = ENC.NUM_COMIDAS_NO_PREPARADA_CASA AND CAT13.CATEGORIA_VARIABLE = 'Número de comidas no preparadas en casa'
INNER JOIN CATALOGO_VARIABLE CAT14 ON CAT14.CODIGO = ENC.NUM_COMIDAS_RAPIDA_PIZZERIA AND CAT14.CATEGORIA_VARIABLE = 'Número de comidas de comida rápida o pizzería'
INNER JOIN CATALOGO_VARIABLE CAT15 ON CAT15.CODIGO = ENC.DIAS_FISIC_ACTIVO_ALMENOS_60MIN AND CAT15.CATEGORIA_VARIABLE = 'Días físicamente activos al menos 60 min'
INNER JOIN CATALOGO_VARIABLE CAT16 ON CAT16.CODIGO = ENC.HORAS_MIRA_TV_VIDEO_ULT_30DIAS AND CAT16.CATEGORIA_VARIABLE = 'Horas mirando televisión o videos pasados 30 días'
INNER JOIN CATALOGO_VARIABLE CAT17 ON CAT17.CODIGO = ENC.HORAS_COMPUTADOR_ULT_30DIAS AND CAT17.CATEGORIA_VARIABLE = 'Horas de uso de la computadora pasados 30 días';

COMMIT;

